### ISSUE TITLE
ISSUE: Upgraded to v 0.3.0-b41 from b39 and all my mail sensors became unavailable

### ISSUE THREAD

**Issue by riddledaxis** [moralmunky/Home-Assistant-Mail-And-Packages#359]
**Describe the bug**
After the server had restarted all of my mail sensors were showing as 'unavailable' and orphaned in HA entities.

I have then tried reinstalling the add-on from the HACS menu to the latest working version for me, which was b39 but the sensors were still showing as unavailable.

I then tried removing the integration from Integrations and HACS, restarting the server and then re-installing version b39. But no sensors were created when I configured the Integration (bottom screenshot). So I now have no sensors configured at all.

**Environment (please complete the following information):**
HassOS 5.10, HA Supervisor: supervisor-2021.01.7, HA Core: core-2021.1.5, M+P: 0.3.0-b39

**Logs**
```
2021-02-01 21:58:02 INFO (MainThread) [custom_components.mail_and_packages] Successfully removed sensor from the mail_and_packages integration
2021-02-01 21:58:02 INFO (MainThread) [custom_components.mail_and_packages] Version 0.3.0-b39 is starting, if you have any issues please report them here: http://github.com/moralmunky/Home-Assistant-Mail-And-Packages
2021-02-01 21:58:03 ERROR (MainThread) [custom_components.mail_and_packages] Unexpected error fetching Mail and Packages (outlook.office365.com) data: 'image_name'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 144, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 132, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/mail_and_packages/__init__.py", line 64, in async_update_data
    return await hass.async_add_executor_job(process_emails, hass, config)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/mail_and_packages/helpers.py", line 105, in process_emails
    fetch(hass, config, account, data, sensor)
  File "/config/custom_components/mail_and_packages/helpers.py", line 175, in fetch
    image_name = data[const.ATTR_IMAGE_NAME]
KeyError: 'image_name'
2021-02-01 21:58:03 DEBUG (MainThread) [custom_components.mail_and_packages] Finished fetching Mail and Packages (outlook.office365.com) data in 0.826 seconds
2021-02-01 21:58:03 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.mail_and_packages
2021-02-01 21:58:03 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mail_and_packages platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/mail_and_packages/sensor.py", line 27, in async_setup_entry
    sensors.append(ImagePathSensors(hass, entry, variable, coordinator, unique_id))
  File "/config/custom_components/mail_and_packages/sensor.py", line 129, in __init__
    self._image = self.coordinator.data[const.ATTR_IMAGE_NAME]
TypeError: 'NoneType' object is not subscriptable
```

**Screenshots**
![image](https://user-images.githubusercontent.com/47009467/106520780-2ebecd00-64d5-11eb-87ec-f316dccc3cf8.png)
![image](https://user-images.githubusercontent.com/47009467/106520797-34b4ae00-64d5-11eb-914c-306b0028fe13.png)
![image](https://user-images.githubusercontent.com/47009467/106523583-3e401500-64d9-11eb-8cc8-d038a8eda1b1.png)

**Comment by firstof9** [comment]
b39 had a bug that was fixed in b40, what happens when you upgrade to b41?

**Comment by riddledaxis** [comment]
I have run the upgrade from HACS, and after the server reboot, the HA log showed Amazon delivery email being picked up by M+P.

Unfortunately, there will still no sensors in HA and I got this error
```
2021-02-02 17:08:25 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mail_and_packages platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/mail_and_packages/sensor.py", line 28, in async_setup_entry
    sensors.append(ImagePathSensors(hass, entry, variable, coordinator, unique_id))
  File "/config/custom_components/mail_and_packages/sensor.py", line 130, in __init__
    self._image = self.coordinator.data[const.ATTR_IMAGE_NAME]
TypeError: 'NoneType' object is not subscriptable
```
I reloaded the integration from Settings>Integrations and the 23 entities popped up.
```
2021-02-02 17:09:33 DEBUG (MainThread) [custom_components.mail_and_packages] Finished fetching Mail and Packages (outlook.office365.com) data in 3.811 seconds
2021-02-02 17:09:33 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.mail_and_packages
2021-02-02 17:09:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.mail_and_packages entity: sensor.mail_amazon_packages_delivered
2021-02-02 17:09:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.mail_and_packages entity: sensor.mail_amazon_hub_packages
2021-02-02 17:09:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.mail_and_packages entity: sensor.mail_amazon_packages
2021-02-02 17:09:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.mail_and_packages entity: sensor.mail_dhl_delivered
2021-02-02 17:09:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.mail_and_packages entity: sensor.mail_dhl_delivering
2021-02-02 17:09:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.mail_and_packages entity: sensor.mail_dhl_packages
2021-02-02 17:09:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.mail_and_packages entity: sensor.mail_fedex_delivered
2021-02-02 17:09:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.mail_and_packages entity: sensor.mail_fedex_delivering
2021-02-02 17:09:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.mail_and_packages entity: sensor.mail_fedex_packages
2021-02-02 17:09:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.mail_and_packages entity: sensor.mail_hermes_delivered
2021-02-02 17:09:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.mail_and_packages entity: sensor.mail_hermes_delivering
2021-02-02 17:09:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.mail_and_packages entity: sensor.mail_hermes_packages
2021-02-02 17:09:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.mail_and_packages entity: sensor.mail_updated
2021-02-02 17:09:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.mail_and_packages entity: sensor.mail_royal_mail_delivered
2021-02-02 17:09:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.mail_and_packages entity: sensor.mail_royal_mail_delivering
2021-02-02 17:09:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.mail_and_packages entity: sensor.mail_royal_mail_packages
2021-02-02 17:09:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.mail_and_packages entity: sensor.mail_ups_delivered
2021-02-02 17:09:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.mail_and_packages entity: sensor.mail_ups_delivering
2021-02-02 17:09:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.mail_and_packages entity: sensor.mail_ups_packages
2021-02-02 17:09:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.mail_and_packages entity: sensor.mail_packages_delivered
2021-02-02 17:09:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.mail_and_packages entity: sensor.mail_packages_in_transit
2021-02-02 17:09:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.mail_and_packages entity: sensor.mail_image_system_path
2021-02-02 17:09:33 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new sensor.mail_and_packages entity: sensor.mail_image_url
2021-02-02 17:09:33 ERROR (MainThread) [homeassistant.helpers.condition] Error during template condition: UndefinedError: 'None' has no attribute 'last_changed'
```

The integration is now working. But I do not understand why this issue, occurred as the software levels were all the same on this upgrade as they were yesterday when it all went wrong?

**Comment by samlroberts** [comment]
Anyone else having this problem still? I've tried installing different versions, removing completely and reinstalling, still getting the same problem as above.

**Comment by riddledaxis** [comment]
@samlroberts I fixed the issue by doing the following:

1. removing M+P from Configuration>Integrations, I didn't do anything to my Lovelace card(s), just left them as they were 
2. uninstalled the M+P integration from HACS, 
3. restarted my HA,
4. reinstalled M+P in HACS, I installed 3.0-b41,
5. restarted the HA server,
6. Add the Integration in Configuration>Integrations 

At this point for me, the M+P sensors weren't created.

So I reloaded the Integration by clicking on the 3 dots on the Mail and Packages card in Configuration>Integrations, and the sensors were created and everything started working again.

Hope this works for you as well

**Comment by samlroberts** [comment]
@riddledaxis Thanks. I followed those steps, got the error `2021-02-05 07:06:22 ERROR (MainThread) [custom_components.mail_and_packages] Unexpected error fetching Mail and Packages (imap.gmail.com) data: [Errno 2] No such file or directory: '/config/www/mail_and_packages/'` so I manually created it, reloaded again, and the sensors got created, I can find them Entities page, and my lovelace card displays them again. It's weird, they don't show up on the card on the Integrations page:

![image](https://user-images.githubusercontent.com/3945600/107032705-3b1b8200-6782-11eb-930f-022823f2e7cb.png)

But they seem to be working anyway, so I think I'm all set. 

Thanks again,

**Comment by riddledaxis** [comment]
@samlroberts if you click on the 3 dots on the card in your last post. select reload and the entities (sensors) should appear on it.

**Comment by samlroberts** [comment]
@riddledaxis I did that several times, and also restarted HA a couple times. Either that or just waiting a while worked and they showed up.

**Comment by riddledaxis** [comment]
@samlroberts Glad that everything got sorted for you 👍
