### ISSUE TITLE
ISSUE: Issues with sensors not being set correctly and multiple errors.

### ISSUE THREAD

**Issue by SimplySynced** [moralmunky/Home-Assistant-Mail-And-Packages#621]
**Describe the bug**
Just installed this plugin as it looks amazing.  I'm noticing the following.  USPS is only telling me one mail when there is several when I look at the actual email.  I know there is mention if you have multiple folders to create multiple instances of the integration.  However, when I looked at just my sensor for setting up USPS it is also adding an amazon camera.  Lastly in the log I get this consistantly.  

Entity sensor.mail_usps_packages (<class 'custom_components.mail_and_packages.sensor.PackagesSensor'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.mail_image_system_path (<class 'custom_components.mail_and_packages.sensor.ImagePathSensors'>) implements device_state_attributes. Please report it to the custom component author.
Entity sensor.mail_image_url (<class 'custom_components.mail_and_packages.sensor.ImagePathSensors'>) implements device_state_attributes. Please report it to the custom component author.
Entity camera.mail_usps_camera (<class 'custom_components.mail_and_packages.camera.MailCam'>) implements device_state_attributes. Please report it to the custom component author.
Entity camera.mail_amazon_delivery_camera (<class 'custom_components.mail_and_packages.camera.MailCam'>) implements device_state_attributes. Please report it to the custom component author.

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: [e.g. RPi3/NUC/Synology]
 - Home Assistant version: core-2021.12.10
 - Hassio/Docker/Core? Core
 - Component version: 0.3.3-2

**Logs**
2022-01-25 22:05:08 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Camera Update: usps_camera
2022-01-25 22:05:08 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Custom No Mail: None
2022-01-25 22:05:08 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Camera Update: amazon_camera
2022-01-25 22:05:08 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Custom No Mail: None
2022-01-25 22:05:20 ERROR (Thread-11) [pychromecast.socket_client] [Living Room Soundbar(10.1.1.167):8009] Failed to connect to service ServiceInfo(type='mdns', data='SmartCast-Sound-Bar--d66fa8cc6bda216e681989c753ff73a5._googlecast._tcp.local.'), retrying in 5.0s
2022-01-25 22:05:38 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Camera Update: usps_camera
2022-01-25 22:05:38 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Custom No Mail: None
2022-01-25 22:05:38 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Camera Update: amazon_camera
2022-01-25 22:05:38 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Custom No Mail: None
2022-01-25 22:06:08 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Camera Update: usps_camera
2022-01-25 22:06:08 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Custom No Mail: None
2022-01-25 22:06:08 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Camera Update: amazon_camera
2022-01-25 22:06:08 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Custom No Mail: None
2022-01-25 22:06:14 INFO (Wemo Events Thread) [pywemo.subscribe] Resubscribe for <Subscription basicevent "Fish Whites">
2022-01-25 22:06:14 INFO (Wemo Events Thread) [pywemo.subscribe] Resubscribe for <Subscription basicevent "Craft Light">
2022-01-25 22:06:14 INFO (Wemo Events Thread) [pywemo.subscribe] Resubscribe for <Subscription basicevent "Fish Blues">
2022-01-25 22:06:38 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Camera Update: usps_camera
2022-01-25 22:06:38 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Custom No Mail: None
2022-01-25 22:06:38 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Camera Update: amazon_camera
2022-01-25 22:06:38 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Custom No Mail: None
2022-01-25 22:07:08 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Camera Update: usps_camera
2022-01-25 22:07:08 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Custom No Mail: None
2022-01-25 22:07:08 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Camera Update: amazon_camera
2022-01-25 22:07:08 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Custom No Mail: None
2022-01-25 22:07:38 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Camera Update: usps_camera
2022-01-25 22:07:38 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Custom No Mail: None
2022-01-25 22:07:38 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Camera Update: amazon_camera
2022-01-25 22:07:38 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Custom No Mail: None
2022-01-25 22:08:08 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Camera Update: usps_camera
2022-01-25 22:08:08 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Custom No Mail: None
2022-01-25 22:08:08 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Camera Update: amazon_camera
2022-01-25 22:08:08 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Custom No Mail: None
2022-01-25 22:08:38 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Camera Update: usps_camera
2022-01-25 22:08:38 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Custom No Mail: None
2022-01-25 22:08:38 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Camera Update: amazon_camera
2022-01-25 22:08:38 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Custom No Mail: None
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Created: 25-Jan-2022, Today: 25-Jan-2022
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Image Name: 67ead451-9c8d-4870-a09d-a4de7d535c81.gif
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Copying /config/custom_components/mail_and_packages/mail_none.gif to /config/custom_components/mail_and_packages/images/67ead451-9c8d-4870-a09d-a4de7d535c81.gif
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Image name: 67ead451-9c8d-4870-a09d-a4de7d535c81.gif
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Created: 22-Jan-2022, Today: 25-Jan-2022
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Created: 25-Jan-2022, Today: 25-Jan-2022
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Image Name: 76777e30-cf20-42d4-be80-bb9a552acc42.jpg
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Copying /config/custom_components/mail_and_packages/no_deliveries.jpg to /config/custom_components/mail_and_packages/images/amazon/76777e30-cf20-42d4-be80-bb9a552acc42.jpg
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Amazon Image Name: 76777e30-cf20-42d4-be80-bb9a552acc42.jpg
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Image path: custom_components/mail_and_packages/images/
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Sensor: mail_updated Count: Jan-25-2022 10:08 PM
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Attempting to find mail from (['auto-reply@usps.com']) with subject (Item Delivered)
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (FROM "auto-reply@usps.com" SUBJECT "Item Delivered" SINCE "25-Jan-2022")
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] DEBUG email_search value: ('OK', [b''])
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Search for (['auto-reply@usps.com']) with subject (Item Delivered) results: b'' count: 0
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Sensor: usps_delivered Count: 0
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Attempting to find mail from (['auto-reply@usps.com']) with subject (Expected Delivery on)
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (FROM "auto-reply@usps.com" SUBJECT "Expected Delivery on" SINCE "25-Jan-2022")
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] DEBUG email_search value: ('OK', [b''])
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Searching for (Your item is out for delivery) in (1) emails
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Search for (Your item is out for delivery) count results: 0
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Search for (['auto-reply@usps.com']) with subject (Expected Delivery on) results: b'' count: 0
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Attempting to find mail from (['auto-reply@usps.com']) with subject (Out for Delivery)
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (FROM "auto-reply@usps.com" SUBJECT "Out for Delivery" SINCE "25-Jan-2022")
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] DEBUG email_search value: ('OK', [b''])
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Searching for (Your item is out for delivery) in (1) emails
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Search for (Your item is out for delivery) count results: 0
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Search for (['auto-reply@usps.com']) with subject (Out for Delivery) results: b'' count: 0
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Sensor: usps_delivering Count: 0
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Attempting to find mail from (['auto-reply@usps.com']) with subject (Delivery Exception)
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (FROM "auto-reply@usps.com" SUBJECT "Delivery Exception" SINCE "25-Jan-2022")
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] DEBUG email_search value: ('OK', [b''])
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Search for (['auto-reply@usps.com']) with subject (Delivery Exception) results: b'' count: 0
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Sensor: usps_exception Count: 0
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Attempting to find Informed Delivery mail
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Informed delivery search date: 25-Jan-2022
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (OR OR FROM "USPSInformedDelivery@usps.gov" FROM "USPSInformeddelivery@email.informeddelivery.usps.com" FROM "USPSInformeddelivery@informeddelivery.usps.com" SUBJECT "Your Daily Digest" SINCE "25-Jan-2022")
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] DEBUG email_search value: ('OK', [b'8'])
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Cleaning up image directory: /config/custom_components/mail_and_packages/images/
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Checking for overlay files in: /config/custom_components/mail_and_packages/images/
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Copying file to: /config/custom_components/mail_and_packages/images/overlay.png
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Copying file to: /config/custom_components/mail_and_packages/images/vignette.png
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Copying file to: /config/custom_components/mail_and_packages/images/white.png
2022-01-25 22:08:44 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Informed Delivery email found processing...
2022-01-25 22:08:45 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Removing duplicate images.
2022-01-25 22:08:45 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Placeholder image found using: image-no-mailpieces700.jpg.
2022-01-25 22:08:45 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Removing USPS announcement images.
2022-01-25 22:08:45 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Image Count: 1
2022-01-25 22:08:45 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Resizing images to 724x320...
2022-01-25 22:08:45 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Creating array of image files...
2022-01-25 22:08:45 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Generating animated GIF
2022-01-25 22:08:45 INFO (SyncWorker_8) [custom_components.mail_and_packages.helpers] Mail image generated.
2022-01-25 22:08:45 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Generating mp4: /config/custom_components/mail_and_packages/images/67ead451-9c8d-4870-a09d-a4de7d535c81.mp4
2022-01-25 22:08:45 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Sensor: usps_mail Count: 1
2022-01-25 22:08:45 DEBUG (SyncWorker_8) [custom_components.mail_and_packages.helpers] Sensor: usps_packages Count: 0
2022-01-25 22:08:45 DEBUG (MainThread) [custom_components.mail_and_packages] Finished fetching Mail and Packages (imap.gmail.com) data in 3.290 seconds (success: True)
2022-01-25 22:08:45 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Updating system image path to: custom_components/mail_and_packages/images/
2022-01-25 22:09:08 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Camera Update: usps_camera
2022-01-25 22:09:08 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Custom No Mail: None
2022-01-25 22:09:08 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Camera Update: amazon_camera
2022-01-25 22:09:08 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Custom No Mail: None
2022-01-25 22:09:38 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Camera Update: usps_camera
2022-01-25 22:09:38 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Custom No Mail: None
2022-01-25 22:09:38 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Camera Update: amazon_camera
2022-01-25 22:09:38 DEBUG (MainThread) [custom_components.mail_and_packages.camera] Custom No Mail: None

**Comment by firstof9** [comment]
This is already fixed in the beta version.

**Comment by SimplySynced** [comment]
Excellent, I'll update to beta and give it a try.

**Comment by SimplySynced** [comment]
I installed the latest beta and restarted.  I still get the amazon cam even if I didn't choose it.  I also am only being told 1 peice of mail even though I have both.

**Comment by firstof9** [comment]
> I still get the amazon cam even if I didn't choose it.

It doesn't have an configuration option to disable it, you can however disable the entity itself.


> I also am only being told 1 peice of mail even though I have both.

USPS mail advertisements are filtered out and not counted.

**Comment by SimplySynced** [comment]
When it comes to the amazon camera, I have my amazon emails into a separate folder then the usps so if I setup another sensor for just the amazon account then I'll have 2 cameras called amazon will I not?  I guess not a huge issue.  I have 3 pieces of mail according to my email but it still is only showing 1 piece of mail.  They are not USPS mail advertisements.

**Comment by firstof9** [comment]
> I have 3 pieces of mail according to my email but it still is only showing 1 piece of mail. They are not USPS mail advertisements.

These are the scanned black and white mail images?
My integration is reporting 8 pieces, but there's 10 coming, the extra 2 are junk mail.

**Comment by SimplySynced** [comment]
I did a complete uninstall and reinstall and it seems the past couple days I'm getting the correct usps mail count.  However I do have an issue with amazon packages.  I got a shipping-notification email.  Here is the relevant portion of the log.  I get nothing on the sensor count. 

`2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Amazon emails found: 1
2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Email Multipart: True
2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Content Type: multipart/alternative
2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Amazon Subject: Your Amazon.com order #112-7619217-6877007 has shipped
2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] RAW EMAIL: Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: 7bit
Amazon Shipping Confirmation
https://www.amazon.com?ie=UTF8&ref_=scr_home
____________________________________________________________________
Hi Rob, your package will arrive:
Wednesday, February 2
Track your package:
https://www.amazon.com/gp/your-account/ship-track?ie=UTF8&orderId2-7619217-6877007&packageIndex=0&shipmentId=TBNKTs0Cw&ref_=scr_pt_tp_t
On the way:
1 item
Order #112-7619217-6877007
An Amazon driver may contact you by text message or call you for help on the day of delivery.
Ship to:
[REDACTED]
Shipment total:
$16.95
Return or replace items in Your orders
https://www.amazon.com/gp/css/order-history?ie=UTF8&ref_=scr_yo
Learn how to recycle your packaging at Amazon Second Chance(https://www.amazon.com/amsc?ref_=ascyorn).
____________________________________________________________________
Unless otherwise noted, items sold by Amazon are subject to sales tax in select states in accordance with the applicable laws of that state. If your order contains one or more items from a seller other than Amazon, it may be subject to state and local sales tax, depending upon the sellers business policies and the location of their operations. For more information, go to tax and seller information:
http://www.amazon.com/gp/help/customer/display.html?ie=UTF8&nodeId 2029700&ref_-=scr_help_tax
Your invoice can be accessed here:
https://www.amazon.com/gp/css/summary/print.html?ie=UTF8&orderID2-7619217-6877007&ref_=scr_od_invoice
This email was sent from a notification-only address that cannot accept incoming email. Do not reply to this message.
2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Looking for: will arrive:
2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] First pass: Wednesday, February 2
2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Arrive Date: Wednesday, February 2
2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Arrive Date: Wednesday, February 2
2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Arrive Date: Wednesday, February 2
2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Looking for: estimated delivery date is:
2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Looking for: guaranteed delivery date is:
2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Looking for: Arriving:
2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Looking for: Arriverà:
2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Looking for: arriving:
2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Amazon email search address: ['shipment-tracking@amazon.ca', 'conferma-spedizione@amazon.ca']
2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (OR FROM "shipment-tracking@amazon.ca" FROM "conferma-spedizione@amazon.ca" SINCE "29-Jan-2022")
2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] DEBUG email_search value: ('OK', [b''])
2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Amazon emails found: 0
2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Amazon email search address: ['shipment-tracking@amazon.co.uk', 'conferma-spedizione@amazon.co.uk']
2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (OR FROM "shipment-tracking@amazon.co.uk" FROM "conferma-spedizione@amazon.co.uk" SINCE "29-Jan-2022")
2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] DEBUG email_search value: ('OK', [b''])
2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Amazon emails found: 0
2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Amazon email search address: ['shipment-tracking@amazon.in', 'conferma-spedizione@amazon.in']
2022-02-01 17:18:43 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (OR FROM "shipment-tracking@amazon.in" FROM "conferma-spedizione@amazon.in" SINCE "29-Jan-2022")
2022-02-01 17:18:44 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] DEBUG email_search value: ('OK', [b''])
2022-02-01 17:18:44 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Amazon emails found: 0
2022-02-01 17:18:44 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Amazon email search address: ['shipment-tracking@amazon.de', 'conferma-spedizione@amazon.de']
2022-02-01 17:18:44 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (OR FROM "shipment-tracking@amazon.de" FROM "conferma-spedizione@amazon.de" SINCE "29-Jan-2022")
2022-02-01 17:18:44 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] DEBUG email_search value: ('OK', [b''])
2022-02-01 17:18:44 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Amazon emails found: 0
2022-02-01 17:18:44 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Amazon email search address: ['shipment-tracking@amazon.it', 'conferma-spedizione@amazon.it']
2022-02-01 17:18:44 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] DEBUG imap_search: (OR FROM "shipment-tracking@amazon.it" FROM "conferma-spedizione@amazon.it" SINCE "29-Jan-2022")
2022-02-01 17:18:44 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] DEBUG email_search value: ('OK', [b''])
2022-02-01 17:18:44 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Amazon emails found: 0
2022-02-01 17:18:44 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Amazon order: ['112-7619217-6877007']
2022-02-01 17:18:44 DEBUG (SyncWorker_3) [custom_components.mail_and_packages.helpers] Sensor: amazon_packages Count: 0`

So it finds it and seems to find the date on the first pass.  Unless I'm understanding this wrong but shouldn't this show up as an "In Transit" Package?

**Comment by firstof9** [comment]
It'll show up in the amazon sensor (all amazon sensors are standalone and not tallied in the cumulative sensors), on the 2nd.
This is [covered in the wiki](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki#amazon).

**Comment by SimplySynced** [comment]
I see, I must of misread and understood originally.  I'll close now that the mail sensors working good and other errors gone since the beta update.  Love this plugin and apologies on the misunderstanding.
