### ISSUE TITLE
ISSUE: USPS double count from notification emails

### ISSUE THREAD

**Issue by moralmunky** [moralmunky/Home-Assistant-Mail-And-Packages#92]
**Describe the bug**
USPS sent two notification regarding the same tracking number. I cannot confirm the consistency of these notifications. Previous behavior the 8:16 email would come before the expected date shown in the email.

7:47 AM - USPS® Expected Delivery on Wednesday, April 15, 2020 arriving by 6:00pm
                 Body: Your item is out for delivery on April 15, 2020 at 7:10 am
8:16 AM - USPS® Expected Delivery on Wednesday, April 15, 2020 arriving by 6:00pm
                 Body: USPS expects to deliver your package on Wednesday, April 15, 2020 arriving by 6:00pm.

**Comment by ronaldheft** [comment]
Seeing the same thing with duplicate packages.

I’ve come up with a work around.

When I receive a duplicate email, it’s because I receive both an expected delivery email and an out for delivery email. I adjusted my mail filters to only place the out for delivery emails in my folder that’s being monitored.

The rules are:

Subject: USPS® Expected Delivery
Must contain: Out for Delivery

Perhaps a fix could be, if we’re not de-duplicating by tracking number, we could at least filter on the out for delivery message.

**Comment by firstof9** [comment]
I'll be testing some code this afternoon that may resolve this.

**Comment by firstof9** [comment]
@ronaldheft 0.2.0-b5 should resolve this as it will now check for 'out for delivery' in the emails.

**Comment by FuzzyMistborn** [comment]
I'm still getting dupes for USPS packages.  Unfortunately the subject line is the same, it's just that the text in the email is slightly different.  Also, the first email comes before ~6am and the second is later.
Early email:
![image](https://user-images.githubusercontent.com/16689090/84048140-abff6580-a979-11ea-8a5c-ad3279c9fe12.png)
Later email:
![image](https://user-images.githubusercontent.com/16689090/84048374-bfaacc00-a979-11ea-8785-742d98dfe790.png)

**Comment by thisisbenwoo** [comment]
Sorry, but I need to reopen ... 
I point the integration to my Gmail/All Mail mailbox, and for some reason, USPS decided to send me 3 emails this morning all for the same package (package number redacted):

![image](https://user-images.githubusercontent.com/45885373/84047662-61bdba80-a960-11ea-9010-1254b10f3ea1.png)

The integration reports:
![image](https://user-images.githubusercontent.com/45885373/84048152-874ac400-a960-11ea-9462-8e49c1bdfaf8.png)

And today's Informed delivery shows:
![image](https://user-images.githubusercontent.com/45885373/84048864-c2e58e00-a960-11ea-91a8-6353d49097cd.png)

So duplication is still there. I hope this helps.

**Comment by firstof9** [comment]
Do the emails contain "out for delivery" ?
Emails that shouldn't get counted contain text similar to the following:
```
Hello ,

USPS expects to deliver your package by Monday, June 8, 2020 arriving by 8:00pm.

Tracking Number:
```

**Comment by FuzzyMistborn** [comment]
For me they seem to be counted still.  For example I had 3 packages delivered yesterday, but my count was 6 (then dropped to 3 when packages were delivered).
![image](https://user-images.githubusercontent.com/16689090/84057721-13bbad80-a986-11ea-862d-d6489e710f37.png)

**Comment by thisisbenwoo** [comment]
No, the email sdo not say "out for delivery". This is the full text of the email:

![image](https://user-images.githubusercontent.com/45885373/84059942-4064ca80-a970-11ea-9713-6f556102f9a7.png)
So I got 3 of these today.

**Comment by firstof9** [comment]
Very strange, I have 2 emails from USPS saying 1 for today and one for the 12th, but neither are showing up as in transit.

Either of you running the latest beta?

**Comment by FuzzyMistborn** [comment]
I'm on the 2.0 release, I didn't see anything in either beta that affected USPS.  Can update and see next time I get a USPS package if that helps.

**Comment by thisisbenwoo** [comment]
Sure np


*Ben Woo*
(212) 724-1188
*this*is*ben*woo*@gmail.com <http://gmail.com/>*

**Comment by firstof9** [comment]
Only wonder since there could have been an unintended regression.

**Comment by moralmunky** [comment]
I set the testing date in the sensor.py back to the date when I first noticed it I get the following logs.

```
Attempting to find mail from auto-reply@usps.com with subject 1 Item Delivered
Found from auto-reply@usps.com with subject 1 Item Delivered, b'94'

Attempting to find mail from auto-reply@usps.com with subject 1 Expected Delivery on
Searching for out for delivery in emails
Found out for delivery in email
Found out for delivery in email
Found from auto-reply@usps.com with subject 1 Expected Delivery on, b'88 89'
```

I search the raw source of the incorrectly matched message to see if 'out for delivery' appeared somewhere else causing the false positive. It didn't find a thing.

It's defiantly in the [find_text](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/945a4478e2f382e66a4ca3d34925071634e8deed/custom_components/mail_and_packages/sensor.py#L616-L631) function that it's accepting all emails found as having 'out for delivery' in it.

**Comment by firstof9** [comment]
If you guys want to give an alpha a try (i haven't tested it locally yet) here's 2 files to try:

https://raw.githubusercontent.com/firstof9/Home-Assistant-Mail-And-Packages/0.2.x/custom_components/mail_and_packages/sensor.py

https://raw.githubusercontent.com/firstof9/Home-Assistant-Mail-And-Packages/0.2.x/custom_components/mail_and_packages/const.py

I'll be testing them later this afternoon.

**Comment by moralmunky** [comment]
I wasn't just typing this when I got this last message.

Looking at the .find() method. It returns the position of the first match or returns a -1. So the turn of -1 needs to be excluded or it 

```
Searching for out for delivery in emails
Found -1 in email
Found for delivery in email
Found 3451 in email
Found for delivery in email
```l

**Comment by thisisbenwoo** [comment]
OK, I just downloaded the alpha, and restarted HA. It read my All Mail mailbox, and it concluded that I have no packages :-(

It should have listed that I have ONE package.

![image](https://user-images.githubusercontent.com/45885373/84077131-b9bde680-a98b-11ea-9045-56b016cbe8cd.png)

**Comment by moralmunky** [comment]
It's not matching anything. In either method to find the text the email need to be decoded. Outputting `email_msg` is still encoded so the phrase is being split.

```
<p style=3D"text-align: left;font-family: sans-serif;">Your item is out for=
 delivery on April 15, 2020 at 7:10 am
```

**Comment by firstof9** [comment]
Alright, made a few tweaks should work better:
[sensor.py](https://raw.githubusercontent.com/firstof9/Home-Assistant-Mail-And-Packages/0.2.x/custom_components/mail_and_packages/sensor.py)
[const.py](https://raw.githubusercontent.com/firstof9/Home-Assistant-Mail-And-Packages/0.2.x/custom_components/mail_and_packages/const.py)

**Comment by moralmunky** [comment]
It's returning None.
```
Searching for out for delivery in emails
Find results: None
Find results: None
Found from auto-reply@usps.com with subject 1 Expected Delivery on, b'88 89'
```

I have find returning correct results using quopri.decodestring.

```
def find_textold(sdata, account, search):
    _LOGGER.debug("Searching for %s in emails", search)
    mail_list = sdata.split()
    count = 0

    for i in mail_list:
        typ, data = account.fetch(i, '(RFC822)')
        for response_part in data:
            if isinstance(response_part, tuple):
                msg = email.message_from_bytes(response_part[1])
                email_msg = quopri.decodestring(str(msg.get_payload(0)))
                email_msg = email_msg.decode('utf-8')
                #_LOGGER.debug("Found %s", email_msg)
                text_found = email_msg.find(search)
                _LOGGER.debug("Find results: %s", text_found)
                if text_found > 0:
                    _LOGGER.debug("Found %s in email", search)
                    count += 1

    return count
```

There is a secondary issue.

Looking back at the logs I've shared, this line below continues to appear meaning it is evaluating the find text then moving on to the [else on line 586](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/945a4478e2f382e66a4ca3d34925071634e8deed/custom_components/mail_and_packages/sensor.py#L584-L589) which is replacing the sensor values back to 2.

`Found from auto-reply@usps.com with subject 1 Expected Delivery on, b'88 89'`

**Comment by moralmunky** [comment]
I had some debug messages confusing me.

Try this [sensor.py](https://raw.githubusercontent.com/moralmunky/Home-Assistant-Mail-And-Packages/dev/custom_components/mail_and_packages/sensor.py) from the dev branch.

**Comment by thisisbenwoo** [comment]
Got a notification that the setup of mail_and_packages sensor failed

**Comment by moralmunky** [comment]
Try using the all the files from the DEV branch instead.
https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/tree/dev

**Comment by thisisbenwoo** [comment]
Just tried the dev branch, and it _looks_ like it is correct.

**Comment by moralmunky** [comment]
So to confirm, USPS packages sensor now only shows 1 where it previously showed 3?

**Comment by thisisbenwoo** [comment]
@moralmunky, YES

**Comment by firstof9** [comment]
I've fixed the regex and used the quopri decode you're using as well @moralmunky

[sensor.py](https://raw.githubusercontent.com/firstof9/Home-Assistant-Mail-And-Packages/0.2.x/custom_components/mail_and_packages/sensor.py)

**Comment by FuzzyMistborn** [comment]
I got nothing today though I have two packages out for delivery.

**Comment by thisisbenwoo** [comment]
Good morning all. Just waking up, but the first thing I noticed is that it's showing no USPS mail (which makes sense since I have not received my Informed Delivery notice yet). But Amazon shows 1 package, but I think that is referring to a packaged delivered last night.

![image](https://user-images.githubusercontent.com/45885373/84154786-621b8b80-aa1c-11ea-8ac3-5056c2397714.png)

Based on my manual tracking, I should not be receiving anything today from Amazon. (In fact, if my tracking is accurate, it is a package free day!)

**Comment by firstof9** [comment]
@thisisbenwoo The Amazon part looks for email in the past 3 days, did the email say it was to be delivered today, but you got it early by chance?

**Comment by thisisbenwoo** [comment]
Ah, you nailed it! :-) Email said it would arrive 6/9, but it arrived 6/8. Email was dated 6/7.

Chris, do you think it would help (and if I can help, I'd love to), to document the logic in the README.md or a supplemental doc? I think that would help people (like me) better understand what to look for if there is an anomaly, and not put it in an issue. Just a thought.

**Comment by firstof9** [comment]
We're working on the wiki, feel free to lend a hand.

**Comment by thisisbenwoo** [comment]
Absolutely, what can I do? I'm pretty new to github, so I'm going to need a little direction. Feel free to PM me directly, or to email me direclty.

**Comment by firstof9** [comment]
If you're on the Home Assistant forum feel free to PM me, github doesn't have PMs anymore.

**Comment by FuzzyMistborn** [comment]
Latest beta seems to resolve issues.  3 packages out for delivery, 3 packages showing up in HASS.

**Comment by FuzzyMistborn** [comment]
Updated to the latest version last night. Automation fired this morning at 3am when I got the "package expected today" message as the sensor went to 1. Just now the package went out for delivery and now the sensor is at 3. Only one package is expected today.

**Comment by firstof9** [comment]
@FuzzyMistborn just to confirm it was 1 email that said "out for delivery" or was it there the one that says "delivered today"?
I made a small change for UPS emails with multiple tracking numbers, but it should still work the same.

Also to confirm 'latest beta version'?

**Comment by FuzzyMistborn** [comment]
I had 1 email at 3:47 am (with sensor updating at 3:51) with "Expected Delivery on" and then the second email at 8:13 with "Out for Delivery".  No email with "delivered today"

And yes, latest beta.  0.2.2-b4

**Comment by firstof9** [comment]
b5 should resolve this for you @FuzzyMistborn I tested it on myself since I had the same issue occur today.

**Comment by FuzzyMistborn** [comment]
Fixed for me.  3 packages back to the actual 1 package.  Thanks!

**Comment by moralmunky** [comment]
HA! This one popped up again. The integration is working right. USPS emailed notifications for the same tracking number. Everything is the same except for the delivery time range. This causes the 2 deliveries to show as 3 total packages from USPS and 1 left in transit for the day after the 2 deliveries occurred.

Unless the direction of this integration gets heavier into the tracking numbers, a disclaimer in the wiki for USPS might be sufficient.

7:35 AM Email
Part|Contents
| ----------- | ----------- |
Subject|USPS® Expected Delivery on Wednesday, August 5, 2020 Between 12:15pm and 4:15pm
Body|Hello ,Your item is out for delivery on August 5, 2020 at 7:28 am in CITY, STATE ZIP. USPS expects to deliver your package today between 12:15pm and 4:15pm.

11:45 AM Email
Part|Contents
| ----------- | ----------- |
Subject|USPS® Expected Delivery on Wednesday, August 5, 2020 Between 1:30pm and 5:30pm
Body|Hello ,Your item is out for delivery on August 5, 2020 at 7:28 am in CITY, STATE ZIP. USPS expects to deliver your package today between 1:30pm and 5:30pm.

**Comment by moralmunky** [comment]
HA! This one popped up again. The integration is working right. USPS emailed notifications for the same tracking number. Everything is the same except for the delivery time range. This causes the 2 deliveries to show as 3 total packages from USPS and 1 left in transit for the day after the 2 deliveries occurred.

Unless the direction of this integration gets heavier into the tracking numbers, a disclaimer in the wiki for USPS might be sufficient.

7:35 AM Email
Part|Contents
| ----------- | ----------- |
Subject|USPS® Expected Delivery on Wednesday, August 5, 2020 Between 12:15pm and 4:15pm
Body|Hello ,Your item is out for delivery on August 5, 2020 at 7:28 am in CITY, STATE ZIP. USPS expects to deliver your package today between 12:15pm and 4:15pm.

11:45 AM Email
Part|Contents
| ----------- | ----------- |
Subject|USPS® Expected Delivery on Wednesday, August 5, 2020 Between 1:30pm and 5:30pm
Body|Hello ,Your item is out for delivery on August 5, 2020 at 7:28 am in CITY, STATE ZIP. USPS expects to deliver your package today between 1:30pm and 5:30pm.

**Comment by firstof9** [comment]
Might be able to just do a count of the tracking numbers really. I'll poke around.

**Comment by moralmunky** [comment]
Sorry I didn't get back sooner. Installed the b16 since I saw it was merged.

The error is showing from the new code.

```
sensor.py, line 654, in get_count
    if len(tracking) < len(count):
TypeError: object of type 'int' has no len()
```

**Comment by moralmunky** [comment]
Taking len() off count, I get

b16
sensor.mail_usps_delivering: 2
sensor.mail_usps_packages: 2
sensor.mail_usps_delivered: 0

b15
sensor.mail_usps_delivering: 1
sensor.mail_usps_packages: 3
sensor.mail_usps_delivered: 2

The duplication reduction is working but the delivery emails are not being counted

**Comment by firstof9** [comment]
Yup my logic was wrong, should be:
```
    if tracking:
        # Try to guard against duplicate emails via tracking number
        if len(tracking) < len(count):
            count = len(tracking)
        result[ATTR_TRACKING] = tracking
```
Doing a fix now.

**Comment by moralmunky** [comment]
Replacing that here is the debug
```
2020-08-08 17:49:19 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for mail_and_packages which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-08-08 17:49:20 INFO (MainThread) [custom_components.mail_and_packages] Version 0.2.2-b16 is starting, if you have any issues please report them here: http://github.com/moralmunky/Home-Assistant-Mail-And-Packages
2020-08-08 17:49:21 WARNING (SyncWorker_9) [homeassistant.components.local_file.camera] Could not read camera mail_usps image from file: /home/homeassistant/.homeassistant/www/mail_and_packages/mail_today.mp4
2020-08-08 17:49:22 ERROR (SyncWorker_0) [homeassistant.components.dyson] Not connected to Dyson account. Unable to add devices
2020-08-08 17:49:22 ERROR (MainThread) [homeassistant.setup] Setup failed for dyson: Integration failed to initialize.
2020-08-08 17:49:24 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Config scan interval: 0:05:00
2020-08-08 17:49:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Searching for Amazon delivered email(s)...
2020-08-08 17:49:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon delivered email(s) found: 0
2020-08-08 17:49:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Searching for Amazon image in emails...
2020-08-08 17:49:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] HTML Amazon emails found: 0
2020-08-08 17:49:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon delivered email(s) found: 0
2020-08-08 17:49:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Searching for Amazon image in emails...
2020-08-08 17:49:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] HTML Amazon emails found: 0
2020-08-08 17:49:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon delivered email(s) found: 0
2020-08-08 17:49:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Searching for Amazon image in emails...
2020-08-08 17:49:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] HTML Amazon emails found: 0
2020-08-08 17:49:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon delivered email(s) found: 0
2020-08-08 17:49:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Searching for Amazon image in emails...
2020-08-08 17:49:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] HTML Amazon emails found: 0
2020-08-08 17:49:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find Amazon email with item list ...
2020-08-08 17:49:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon emails found: 0
2020-08-08 17:49:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon emails found: 0
2020-08-08 17:49:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon emails found: 0
2020-08-08 17:49:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon emails found: 0
2020-08-08 17:49:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon Count: 0
2020-08-08 17:49:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find Amazon email with item list ...
2020-08-08 17:49:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon emails found: 0
2020-08-08 17:49:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon emails found: 0
2020-08-08 17:49:25 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon emails found: 0
2020-08-08 17:49:26 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon emails found: 0
2020-08-08 17:49:26 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Amazon order: []
2020-08-08 17:49:26 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from (donotreply_odd@dhl.com) with subject 1 (DHL On Demand Delivery)
2020-08-08 17:49:26 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Searching for (scheduled for delivery TODAY) in (0) emails
2020-08-08 17:49:26 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Search for (scheduled for delivery TODAY) count results: 0
2020-08-08 17:49:26 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Search for (donotreply_odd@dhl.com) with subject 1 (DHL On Demand Delivery) results: b'' count: 0
2020-08-08 17:49:26 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Attempting to find mail from (donotreply_odd@dhl.com) with subject 1 (DHL On Demand Delivery)
2020-08-08 17:49:26 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Searching for (has been delivered) in (0) emails
2020-08-08 17:49:26 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Search for (has been delivered) count results: 0
2020-08-08 17:49:26 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Search for (donotreply_odd@dhl.com) with subject 1 (DHL On Demand Delivery) results: b'' count: 0
2020-08-08 17:49:26 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mail_and_packages platform for sensor
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 71, in async_setup_entry
    sensors.append(PackagesSensor(data, variable))
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 198, in __init__
    self.update()
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 254, in update
    self.data.update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 156, in update
    count[tracking] = info[ATTR_TRACKING]
KeyError: 'tracking'
```

**Comment by firstof9** [comment]
```
    if tracking:
        # Try to guard against duplicate emails via tracking number
        if len(tracking) < len(count):
            count = len(tracking)
    
    result[ATTR_TRACKING] = tracking
```
Indents hate me lol

**Comment by moralmunky** [comment]
Yup, there it is!

**Comment by moralmunky** [comment]
HAHA, in b17 doesn't like the len() around count. Removing it removes the error. Count isn't supposed to be an array is it?

https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/blob/3e7bee18d66f0bfb6e202600cc01b2466584fbf8/custom_components/mail_and_packages/sensor.py#L654

```
2020-08-08 18:11:43 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up mail_and_packages platform for sensor
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 179, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 71, in async_setup_entry
    sensors.append(PackagesSensor(data, variable))
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 198, in __init__
    self.update()
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 254, in update
    self.data.update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 152, in update
    info = get_count(account, sensor, True)
  File "/home/homeassistant/.homeassistant/custom_components/mail_and_packages/sensor.py", line 657, in get_count
    if len(tracking) < len(count):
TypeError: object of type 'int' has no len()
```

**Comment by firstof9** [comment]
Shoot! ya it's just an int

**Comment by firstof9** [comment]
Now it should be good

**Comment by firstof9** [comment]
Also seeing about getting proper tests setup for this too.

**Comment by moralmunky** [comment]
All Clear!
